### ISSUE TITLE
Blank Node sh:property for Date Values is Not Correct

### ISSUE THREAD

**Issue by bequrios** [Kronmar-Bafu/lindas-pylindas#57]
I'm trying to use pylindas for a dataset that has calendar-dates for all observations. My `description.yaml` looks like:

```yaml
date:
    name:
      de: Datum
      en: Date
    description:
      de: Datum der Erhebung
      en: Date of the survey
    dimension-type: Key Dimension
    scale-type: interval
    datatype: date
    path: date
    data-kind: 
      type: temporal
      unit: day
```

The resulting blank node in the cube looks like this:

```turtle
[ a cube:KeyDimension ;
            qudt:scaleType qudt:IntervalScale ;
            schema:description "Datum der Erhebung"@de,
                "Date of the survey"@en ;
            schema:name "Datum"@de,
                "Date"@en ;
            sh:max "2024-12-31" ;
            sh:maxCount 1 ;
            sh:min "1972-12-31" ;
            sh:minCount 1 ;
            sh:nodeKind sh:IRI ;
            sh:path pocag:date ;
            meta:dataKind [ a time:GeneralDateTimeDescription ;
                    time:unitType time:unitDay ] ]
```

but with this information, the cube is not properly displayed in visualize (some weird errors occur). Some reverse engineering with a working cube with calendar-dates (https://environment.ld.admin.ch/foen/ubd01041prod/4) show that the blank node should look like the following:

```turtle
[ a cube:KeyDimension ;
            qudt:scaleType qudt:IntervalScale ;
            schema:description "Datum der Erhebung"@de,
                "Date of the survey"@en ;
            schema:name "Datum"@de,
                "Date"@en ;
            sh:maxInclusive "2024-12-31"^^xsd:date ;
            sh:maxCount 1 ;
            sh:minInclusive "1972-12-31"^^xsd:date ;
            sh:minCount 1 ;
            sh:nodeKind sh:Literal ;
            sh:datatype xsd:date ;
            sh:path pocag:date ;
            meta:dataKind [ a time:GeneralDateTimeDescription ;
                    time:unitType time:unitDay ] ]
```

Manually correcting my cube really leads to success (I'm not sure if really every change is neccessary). The differences in the blank node are:

- sh:maxIncluxive instead of sh:max
- sh:minInclusive instead of sh:min
- datatype xsd:date for sh:maxInclusive and sh:minInclusive instead of xsd:string
- sh:nodeKind sh:Literal instead of sh:IRI
- added sh:datatype xsd:date

So basically, pylindas is somewhat too generic in creating the sh:NodeShape/sh:property blank nodes.
