### ISSUE TITLE
Mapping municipalities with data-kind "spatial-shape" not rendering in Visualize map chart

### ISSUE THREAD

**Issue by patair** [Kronmar-Bafu/lindas-pylindas#61]
Hi everyone

I would like to publish a dataset containing Swiss municipalities with certain associated measurements.
The test CSV file is as follows.

✅ DataFrame préparé :
  GDENR  VALUE_ABS_CONDITION  VALUE_ABS_TOTAL VALUE_PCT_COVERAGE
0     1                  452              881               51.3
1     2                 2144             2934               73.1
2     3                  909             1500               60.6
3     4                  995             1806               55.1

I would like to create a map in Visualize (https://int.visualize.admin.ch/fr/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22nga%22%2C%22includeDrafts%22%3Atrue%7D&dataset=https%3A%2F%2Flindas.admin.ch%2Fofcom%2Fprices%2Fcube%2Fnga_gemeinde%2F1&dataSource=Int and https://s.zazuko.com/RyZwtT).

Validation and Upload are working correctly, but then Visualize does not see any geoshapes when it comes to use the map function (see https://int.visualize.admin.ch/en/create/XnCN-en-FpYp?dataSource=Int).

I'll be gratefull if someone could help.

```
  GDENR:
    name:
      de: Gemeinde Nummer
      fr: Gemeinde Nummer
      it: Gemeinde Nummer
      en: Gemeinde Nummer
    description:
      de: Nummer der Gemeinde (BFS)
      fr: Nummer der Gemeinde (BFS)
      it: Nummer der Gemeinde (BFS)
      en: Nummer der Gemeinde (BFS)
    dimension-type: Key Dimension 
    datatype: URI 
    scale-type: nominal
    path: GDENR 
    mapping:
      type: additive
      base: https://ld.admin.ch/municipality/
    data-kind:
      type: spatial-shape
```
